name: Deploy MP0 to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      # Publish the raw files in src/ as the site
      - uses: actions/upload-pages-artifact@v3
        with:
          path: src
      - id: deployment
        uses: actions/deploy-pages@v4
